---
- name: Build a debian 9 cloud image suitable for Zuul
  hosts: localhost
  vars:
    image_basename: debian-9.qcow2
    image_tmp_dir: "/srv/nodepool/tmp/{{ image_basename }}"
    debian_distro: stretch
  tasks:
    - name: Include debian cloud generic tasks
      include_tasks: debian-cloud.yaml
